-- CREATE TABLE USER --
CREATE TABLE M_USER (
	USER_ID INT AUTO_INCREMENT,
	USER_USERNAME VARCHAR(10) NOT NULL,
	USER_PASSWORD VARCHAR(10) NOT NULL,
	USER_FIRSTNAME VARCHAR(50) NOT NULL,
	USER_LASTNAME VARCHAR(50) NOT NULL,
	USER_GENDER CHAR NOT NULL,
	USER_GPA FLOAT(2) NOT NULL,
	USER_GPAX FLOAT(2) NOT NULL,
	USER_EMAIL VARCHAR(50) NOT NULL,
	USER_STATU VARCHAR(10) NOT NULL,
	PRIMARY KEY (USER_ID)
)

-- CREATE TABLE BRANCH --
CREATE TABLE M_BRANCH (
	BRANCH_ID INT AUTO_INCREMENT,
	BRANCH_INITIAL VARCHAR(5) NOT NULL,
	BRANCH_NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (BRANCH_ID)
)

-- CREATE TABLE MAPPING USER BRANCH --
CREATE TABLE MAPPING_USER_BRANCH (
	MAPPING_USER_DATA_ID INT AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	BRANCH_ID INT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(20) NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	UPDATE_BY VARCHAR(20) NOT NULL,
	PRIMARY KEY (MAPPING_USER_DATA_ID),
	CONSTRAINT FK_BRANCH_USER FOREIGN KEY (USER_ID)
	REFERENCES M_USER(USER_ID),
	CONSTRAINT FK_USER_BRANCH FOREIGN KEY (BRANCH_ID)
	REFERENCES M_BRANCH(BRANCH_ID)	
)

-- CREATE TABLE CAREER --
CREATE TABLE M_CAREER (
	CAREER_ID INT AUTO_INCREMENT,
	CAREER_NAME VARCHAR(50) NOT NULL,
	CAREER_IMAGE VARCHAR(100) NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(20) NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	UPDATE_BY VARCHAR(20) NOT NULL,
	PRIMARY KEY (CAREER_ID)
)

-- CREATE TABLE COURSE --
CREATE TABLE M_COURSE (
	COURSE_ID INT AUTO_INCREMENT,
	COURSE_ INT NOT NULL,
	COURSE_NAME VARCHAR(50) NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(20) NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	UPDATE_BY VARCHAR(20) NOT NULL,
	PRIMARY KEY (COURSE_ID)
)

-- CREATE TABLE MAPPING COURSE SEMESTER --
CREATE TABLE MAPPING_COURSE_SEMESTER (
	MAPPING_COURSE_SEMESTER_ID INT AUTO_INCREMENT,
	COURSE_ID INT NOT NULL,
	COURSE_SEMESTER INT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(20) NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	UPDATE_BY VARCHAR(20) NOT NULL,
	PRIMARY KEY (MAPPING_COURSE_SEMESTER_ID),
	CONSTRAINT FK_COURSE_SEMESTER FOREIGN KEY (COURSE_ID)
	REFERENCES M_COURSE(COURSE_ID),
)

-- CREATE TABLE MAPPING ADVISOR COURSE --
CREATE TABLE MAPPING_ADVISOR_COURSE (
	MAPPING_ADVISOR_COURSE_ID INT AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	COURSE_ID INT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(20) NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	UPDATE_BY VARCHAR(20) NOT NULL,
	PRIMARY KEY (MAPPING_ADVISOR_COURSE_ID),
	CONSTRAINT FK_ADVISOR_COURSE FOREIGN KEY (USER_ID)
	REFERENCES M_USER(USER_ID),
	CONSTRAINT FK_COURSE_ADVISOR FOREIGN KEY (COURSE_ID)
	REFERENCES M_COURSE(COURSE_ID),
)

-- CREATE TABLE MAPPING CAREER COURSE --
CREATE TABLE MAPPING_CAREER_COURSE (
	MAPPING_CAREER_COURSE_ID INT AUTO_INCREMENT,
	CAREER_ID INT NOT NULL,
	COURSE_ID INT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(20) NOT NULL,
	PRIMARY KEY (MAPPING_CAREER_COURSE_ID),
	CONSTRAINT FK_CAREER_COURSE FOREIGN KEY (CAREER_ID)
	REFERENCES M_CAREER(CAREER_ID),
	CONSTRAINT FK_COURSE_CAREER FOREIGN KEY (COURSE_ID)
	REFERENCES M_COURSE(COURSE_ID),
)

-- CREATE TABLE MAPPING STUDENT COURSE --
CREATE TABLE MAPPING_STUDENT_COURSE (
	MAPPING_STUDENT_COURSE_ID INT AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	COURSE_ID INT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(20) NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	UPDATE_BY VARCHAR(20) NOT NULL,
	PRIMARY KEY (MAPPING_STUDENT_COURSE_ID),
	CONSTRAINT FK_STUDENT_COURSE FOREIGN KEY (USER_ID)
	REFERENCES M_USER(USER_ID),
	CONSTRAINT FK_COURSE_STUDENT FOREIGN KEY (COURSE_ID)
	REFERENCES M_COURSE(COURSE_ID),
)

-- CREATE TABLE QUESTION --
CREATE TABLE M_QUESTION (
	QUESTION_ID INT AUTO_INCREMENT,
	QUESTION_GROUP INT NOT NULL,
	QUESTION_CHOISE INT NOT NULL,
	QUESTION_PART VARCHAR(25) NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(20) NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	UPDATE_BY VARCHAR(20) NOT NULL,
	QUESTION_STATUS INT NOT NULL,
	PRIMARY KEY (QUESTION_ID)
)

-- CREATE TABLE TYPE --
CREATE TABLE M_TYPE (
	TYPE_ID INT AUTO_INCREMENT,
	TYPE_NAME INT NOT NULL,
	TYPE_CHOISE INT NOT NULL,
	PRIMARY KEY (TYPE_ID)
)

-- CREATE TABLE MAPPING QUESTION TYPE --
CREATE TABLE MAPPING_QUESTION_TYPE (
	MAPPING_QUESTION_TYPE_ID INT AUTO_INCREMENT,
	QUESTION_ID INT NOT NULL,
	QUESTION_GROUP INT NOT NULL,
	QUESTION_NO INT NOT NULL,
	QUESTION_DETAIL VARCHAR(MAX) NOT NULL,
	CAREER_ID INT NOT NULL,
	TYPE_ID INT NOT NULL,
	PRIMARY KEY (MAPPING_QUESTION_TYPE_ID),
	CONSTRAINT FK_QUESTION_TYPE FOREIGN KEY (QUESTION_ID)
	REFERENCES M_QUESTION(QUESTION_ID),
	CONSTRAINT FK_TYPE_QUESTION FOREIGN KEY (TYPE_ID)
	REFERENCES M_TYPE(TYPE_ID),
	CONSTRAINT FK_CAREER_QUESTION FOREIGN KEY (CAREER_ID)
	REFERENCES M_CAREER(CAREER_ID),
)

-- CREATE TABLE MAPPING STUDENT CAREER --
CREATE TABLE MAPPING_STUDENT_CAREER (
	MAPPING_STUDENT_CAREER_ID INT AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	CAREER_ID INT NOT NULL,
	QUESTION_ID INT NOT NULL,
	TYPE_ID INT NOT NULL,
	RAW_SCORE INT NOT NULL,
	TOP_SCORE INT NOT NULL,
	TOTAL_SCORE INT NOT NULL,
	PRIMARY KEY (MAPPING_STUDENT_CAREER_ID),
	CONSTRAINT FK_STUDENT_CAREER FOREIGN KEY (USER_ID)
	REFERENCES M_USER(USER_ID),
	CONSTRAINT FK_CAREER_STUDENT FOREIGN KEY (CAREER_ID)
	REFERENCES M_CAREER(CAREER_ID),
)

-- CREATE TABLE MAPPING STUDENT QUESTION --
CREATE TABLE MAPPING_STUDENT_QUESTION (
	MAPPING_STUDENT_QUESTION_ID INT AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	MAPPING_QUESTION_TYPE_ID INT NOT NULL,
	QUESTION_SCORE INT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	PRIMARY KEY (MAPPING_STUDENT_QUESTION_ID),
	CONSTRAINT FK_STUDENT_QUESTION FOREIGN KEY (USER_ID)
	REFERENCES M_USER(USER_ID),
	CONSTRAINT FK_QUESTION_STUDENT FOREIGN KEY (MAPPING_QUESTION_TYPE_ID)
	REFERENCES M_MAPPING_QUESTION_TYPE(MAPPING_QUESTION_TYPE_ID),
)
